Traceback (most recent call last):
  File "/home/maxbuskirk/.conda/envs/psifour/bin/psi4", line 333, in <module>
    exec(content)
  File "<string>", line 54, in <module>
  File "/home/maxbuskirk/.conda/envs/psifour/lib//python3.9/site-packages/psi4/driver/driver.py", line 1339, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/home/maxbuskirk/.conda/envs/psifour/lib//python3.9/site-packages/psi4/driver/driver.py", line 739, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/maxbuskirk/.conda/envs/psifour/lib//python3.9/site-packages/psi4/driver/procrouting/proc.py", line 885, in select_ccsd_gradient
    return func(name, **kwargs)
  File "/home/maxbuskirk/.conda/envs/psifour/lib//python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2782, in run_ccenergy_gradient
    ccwfn = run_ccenergy(name, **kwargs)
  File "/home/maxbuskirk/.conda/envs/psifour/lib//python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2744, in run_ccenergy
    core.cctransort(ref_wfn)

RuntimeError: 
Fatal Error: PSIO_ERROR: 17 (Incorrect block start address)

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1628027406310/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::read(unsigned long, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::DPD::file4_mat_irrep_row_rd(psi::dpdfile4*, int, int)


Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("SCF_TYPE", "df")
    core.set_global_option("BASIS", "cc-pVDZ")
    core.set_global_option("REFERENCE", "rhf")
    mol.update_geometry()
    mol.symmetrize(1e-3)
--> e, wfn = optimize('CCSD', return_wfn=True)
    oeprop(wfn, "MULLIKEN_CHARGES")
    mol.print_out()
    print_variables()


!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: PSIO_ERROR: 17 (Incorrect block start address)                      !
! Error occurred in file: /scratch/psilocaluser/conda-                             !
!     builds/psi4-multiout_1628027406310/work/psi4/src/psi4/libpsio/error.cc on    !
!     line: 133                                                                    !
! The most recent 5 function calls were:                                           !
! psi::PSIO::read(unsigned long, char const*, char*, unsigned long,                !
!     psi::psio_address, psi::psio_address*)                                       !
! psi::DPD::file4_mat_irrep_row_rd(psi::dpdfile4*, int, int)                       !
!                                                                                  !
!----------------------------------------------------------------------------------!

 
 
+------------------------------------------+ 
| PALMETTO CLUSTER PBS RESOURCES REQUESTED | 
+------------------------------------------+ 
 
mem=62gb,walltime=60:00:00,ncpus=16
 
 
+-------------------------------------+ 
| PALMETTO CLUSTER PBS RESOURCES USED | 
+-------------------------------------+ 
 
cput=00:09:41,mem=2483592kb,walltime=00:20:41,ncpus=16,cpupercent=46,vmem=3280404kb
 
 
